
CREATE TABLE Schema2.[LookupTable1](
	[Lookup1Key] [int] NOT NULL,
	[Lookup1Value] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LookupTable1] PRIMARY KEY CLUSTERED 
(
	[Lookup1Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO