ALTER DATABASE [{dbName}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
go

RESTORE DATABASE [{dbName}] FROM DISK='{filename}' WITH REPLACE
{moveDBFilesScript}
go

ALTER DATABASE [{dbName}] SET MULTI_USER
go