name: develop push

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
      
    - name: install GitVersion
      run: dotnet tool install -g GitVersion.Tool
#    - name: Use GitVersion
#      run: dotnet gitversion /l console /output buildserver
      
#    - name: Install dependencies for AutoVersionsDB.Core
#      run: dotnet restore src\AutoVersionsDB\AutoVersionsDB.Core\AutoVersionsDB.Core.csproj
    - name: Build AutoVersionsDB.Core
      run: dotnet build src\AutoVersionsDB\AutoVersionsDB.Core\AutoVersionsDB.Core.csproj -c debug
#    - name: Install dependencies for AutoVersionsDB.WinApp
#      run: dotnet restore src\AutoVersionsDB\AutoVersionsDB.WinApp\AutoVersionsDB.WinApp.csproj    
    - name: Build AutoVersionsDB.WinApp
      run: dotnet build src\AutoVersionsDB\AutoVersionsDB.WinApp\AutoVersionsDB.WinApp.csproj -c debug
#    - name: Install dependencies for AutoVersionsDB.ConsoleApp
#      run: dotnet restore src\AutoVersionsDB\AutoVersionsDB.ConsoleApp\AutoVersionsDB.ConsoleApp.csproj    
    - name: Build AutoVersionsDB.ConsoleApp
      run: dotnet build src\AutoVersionsDB\AutoVersionsDB.ConsoleApp\AutoVersionsDB.ConsoleApp.csproj -c debug
    - name: Run Integration Tests
      run: dotnet test src\AutoVersionsDB\AutoVersionsDB.Core.IntegrationTests\AutoVersionsDB.Core.IntegrationTests.csproj

